services:
  - type: web
    name: expenses-tracker
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expenses-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false

databases:
  - name: expenses-tracker-db
    plan: free
    databaseName: expenses_tracker
    user: walet_user